["Polar Prancer",
 "Polar Prancer",
 "Glee Barrage",
 "Glee Barrage",
 "Ho Ho Hum",
 "Ho Ho Hum",
 "Emberwick Shell",
 "Emberwick Shell",
 "Snowflake Projection",
 "Snowflake Projection",
 "Concentrated Mattergem",
 "Concentrated Mattergem",
 "Glimmershard",
 "Glimmershard",
 "Scavenger's Boon",
 "Scavenger's Boon",
 "Frosty Friend",
 "Frosty Friend",
 "Little Helper Shell",
 "Little Helper Shell",
 "Silverwing Kestrel",
 "Silverwing Kestrel",
 "Resilient Laurel",
 "Resilient Laurel",
 "Turbulent Weather",
 "Turbulent Weather",
 "Fist Bump",
 "Fist Bump",
 "Tangled Shell",
 "Tangled Shell",
 "Crystalline Shell",
 "Crystalline Shell",
 "Gift Giver",
 "Gift Giver",
 "Cardinal Directive",
 "Cardinal Directive",
 "The Great Pigeon Projection",
 "The Great Pigeon Projection",
 "Spill the Tea",
 "Spill the Tea",
 "Atlas Hauler",
 "Atlas Hauler",
 "Feeling Lucky",
 "Feeling Lucky",
 "Halcyon Shell",
 "Halcyon Shell",
 "No Worries",
 "No Worries",
 "Concentrated Mattergem",
 "Concentrated Mattergem",
 "Glimmershard",
 "Glimmershard",
 "Scavenger's Boon",
 "Scavenger's Boon",
 "Izanagi's Shell",
 "Izanagi's Shell",
 "Lethe's Mercy",
 "Lethe's Mercy",
 "Stasis Entrance",
 "Stasis Entrance",
 "Coppertone Patina",
 "Coppertone Patina",
 "Accidental Dance",
 "Accidental Dance",
 "Ten-Grasp Sword",
 "Ten-Grasp Sword",
 "Ampulance LXXX",
 "Ampulance LXXX",
 "Lethal System",
 "Lethal System",
 "Cross-Step Shuffle",
 "Cross-Step Shuffle",
 "Universal Armor Ornament",
 "Universal Armor Ornament",
 "Harper's Shell",
 "Harper's Shell",
 "Forbidden Visage Mask",
 "Forbidden Visage Mask",
 "Forbidden Visage Helm",
 "Forbidden Visage Helm",
 "Forbidden Visage Cover",
 "Forbidden Visage Cover",
 "Victory Dance",
 "Victory Dance",
 "Atlas Runner",
 "Atlas Runner",
 "Packmaster's Command",
 "Packmaster's Command",
 "Atlas Shell",
 "Atlas Shell",
 "Buy Bye",
 "Buy Bye",
 "Concentrated Mattergem",
 "Concentrated Mattergem",
 "Glimmershard",
 "Glimmershard",
 "Scavenger's Boon",
 "Scavenger's Boon",
 "Pyrrhic Victory",
 "Pyrrhic Victory",
 "Stardevil Shell",
 "Stardevil Shell",
 "Vex Invasion Effects",
 "Vex Invasion Effects",
 "Butterbark",
 "Butterbark",
 "Atlantis Shell",
 "Atlantis Shell",
 "The Machinoform",
 "The Machinoform",
 "Belvedere",
 "Belvedere",
 "Universal Armor Ornament",
 "Universal Armor Ornament",
 "Excessive Elbow Dance",
 "Excessive Elbow Dance",
 "BrayTech DREAM9",
 "BrayTech DREAM9",
 "Looking Out",
 "Looking Out",
 "Forbidden Visage Strides",
 "Forbidden Visage Strides",
 "Forbidden Visage Greaves",
 "Forbidden Visage Greaves",
 "Forbidden Visage Boots",
 "Forbidden Visage Boots",
 "Cowbell",
 "Cowbell",
 "The Old Ways",
 "The Old Ways",
 "Armor Ornament",
 "Armor Ornament",
 "Keeping Score",
 "Keeping Score",
 "Spider Projection",
 "Spider Projection",
 "Concentrated Mattergem",
 "Concentrated Mattergem",
 "Glimmershard",
 "Glimmershard",
 "Scavenger's Boon",
 "Scavenger's Boon",
 "Sneak Attack",
 "Sneak Attack",
 "Spill the Tea",
 "Spill the Tea",
 "Atlas Shell",
 "Atlas Shell",
 "Laguna Cruiser",
 "Laguna Cruiser",
 "Shadow Trespass",
 "Shadow Trespass",
 "Halcyon Shell",
 "Halcyon Shell",
 "Feeling Lucky",
 "Feeling Lucky",
 "Meditative Moment",
 "Meditative Moment",
 "No Worries",
 "No Worries",
 "The Grateful Crane",
 "The Grateful Crane",
 "Polemology",
 "Polemology",
 "R3-Treads",
 "R3-Treads",
 "Belenus Boosters",
 "Belenus Boosters",
 "Leystriders",
 "Leystriders",
 "Halcyon Visage",
 "Halcyon Visage",
 "Heavenly Lance",
 "Heavenly Lance",
 "On Ashen Wings",
 "On Ashen Wings",
 "Persevering Dance",
 "Persevering Dance",
 "Splinter Projection",
 "Splinter Projection",
 "Concentrated Mattergem",
 "Concentrated Mattergem",
 "Glimmershard",
 "Glimmershard",
 "Scavenger's Boon",
 "Scavenger's Boon",
 "Victory Dance",
 "Victory Dance",
 "Atlas Runner",
 "Atlas Runner",
 "Spider Projection",
 "Spider Projection",
 "Amethyst Bloom",
 "Amethyst Bloom",
 "Kitbash Shell",
 "Kitbash Shell",
 "Atlas Hauler",
 "Atlas Hauler",
 "Linear Fusion Dance",
 "Linear Fusion Dance",
 "Mad Son of Seychelles",
 "Mad Son of Seychelles",
 "Refashioned Shapes",
 "Refashioned Shapes",
 "The Old Ways",
 "The Old Ways",
 "Too Hot",
 "Too Hot",
 "Feline Fancy",
 "Feline Fancy",
 "Binary System",
 "Binary System",
 "Armor Ornament",
 "Armor Ornament",
 "Sleek Dance",
 "Sleek Dance",
 "Eramis Projection",
 "Eramis Projection",
 "Concentrated Mattergem",
 "Concentrated Mattergem",
 "Glimmershard",
 "Glimmershard",
 "Scavenger's Boon",
 "Scavenger's Boon",
 "Heavenly Lance",
 "Heavenly Lance",
 "Curtain Call",
 "Curtain Call",
 "Splinter Projection",
 "Splinter Projection",
 "Carbon Blood",
 "Carbon Blood",
 "Persevering Dance",
 "Persevering Dance",
 "Halcyon Visage",
 "Halcyon Visage",
 "On Ashen Wings",
 "On Ashen Wings",
 "Armor Ornament",
 "Armor Ornament",
 "Keeping Score",
 "Keeping Score",
 "Impolite Company",
 "Impolite Company",
 "Propheteer Shell",
 "Propheteer Shell",
 "Nine Days/Nights",
 "Nine Days/Nights",
 "Photodraulic Actuators",
 "Photodraulic Actuators",
 "Coaxial Bonds",
 "Coaxial Bonds",
 "R3-Treads",
 "R3-Treads",
 "Belenus Boosters",
 "Belenus Boosters",
 "Leystriders",
 "Leystriders"]